### ISSUE TITLE
[Features] Idea to PugReworked

### ISSUE THREAD

**Issue by mrc4tt** [brennanmcmicking/PugReworked#1]
Loading the plugin...
The plugin should say-print: PUG Ready - USE: !ready for READY-UP!
Before the match should start the knife round or some-else:
Idea:
1) Possible to VOTE about knife round: Yes or No!
2) Possible to VOTE about OVERTIME need to be enabled: Yes or No!
3) Possible the plugin will set the teamname after the plugin is loaded.
Example for CT: mp_teamname_1 Team_X // **Team_%s** >> Team_mrc4tt (po_oԀ) *Maakun
Example for Terrorist: mp_teamname_2 Team_X  // **Team_%s** >> Team_brennanmc

**EXAMPLE:**
[PUG] Team_mrc4tt (po_oԀ) *Maakun won the knife round. You have 30 seconds to vote. Type !stay or !switch to cast your vote.

Ⓨ mrc4tt (po_oԀ) *Maakun‎ : !stay
[PUG] You have voted to stay.
//It should print-say here when it will starting the match!
**Example:** 
[PUG] Match will start about X seconds.

End of the Match - after CT or Terrorist with 16 rounds + if overtime is enabled!:
The plugin needs to print-say: %Team% won the match with X-X. GGWP!

After CT or T did win the match:
It shouldn't do this after:
mrc4tt (po_oԀ) *Maakun‎ : !unready
[PUG] Match has already started. **<< Match shouldn't be started after CT or T team did win!**

**TODO // IDEA**
!pause // Unlimited pause! (both team need to !unpause) //Text: X did request pause, next round will be paused!
!timeout // 3 timeout + 30 secs //Text: X did request timeout, will unpause automatically!
!tech/!tec // Unlimited pause! (both team need to !unpause) //Text: X did requested technical pause, next round will be paused!

**Adding as an option: Possible to VOTE which game/max-rounds or some-else**
MR12 **>>** 24 rounds
MR15 **>>** 30 rounds
MR30(Full30) **>>** All rounds (played out) mp_match_can_clinch 0

**Comment by mrc4tt** [comment]
@brennanmcmicking idea/todo/features here! =D

**Comment by brennanmcmicking** [comment]
I'm closing this because I've branched it off into separate issues.
